# Generated by Django 4.1.dev20220512184403 on 2022-06-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carrito_carrito_item_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='idCategoria',
            new_name='id',
        ),
    ]
