# Generated by Django 4.1.dev20220512184403 on 2022-06-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_idcategoria_categoria_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de carrito'),
        ),
        migrations.AlterField(
            model_name='carrito_item',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Item carrito'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de producto'),
        ),
    ]
